networks:
  net:
    driver: bridge

services:
  # 1. База данных PostgreSQL
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - net
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/vagrant/services/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  # 2. Очередь сообщений RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-queue
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
    networks:
      - net

  # 3. Session Service (управление сессиями)
  session-service:
    image: ollyvala/session-service:1.0
    container_name: session-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "8081:8081"
    networks:
      - net
    depends_on:
      - postgres

  # 4. Hotel Service (управление отелями)
  hotel-service:
    image: ollyvala/hotel-service:1.0
    container_name: hotel-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotels_db
    ports:
      - "8082:8082"
    networks:
      - net
    depends_on:
      - postgres
    restart: on-failure

  # 5. Payment Service (оплата)
  payment-service:
    image: ollyvala/payment-service:1.0
    container_name: payment-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
    ports:
      - "8084:8084"
    networks:
      - net
    depends_on:
      - postgres

  # 6. Loyalty Service (программа лояльности)
  loyalty-service:
    image: ollyvala/loyalty-service:1.0
    container_name: loyalty-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balances_db
    ports:
      - "8085:8085"
    networks:
      - net
    depends_on:
      - postgres

  # 7. Report Service (статистика)
  report-service:
    image: ollyvala/report-service:1.0
    container_name: report-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statistics_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
    ports:
      - "8086:8086"
    networks:
      - net
    depends_on:
      - postgres
      - rabbitmq

  # 8. Booking Service (бронирование)
  booking-service:
    image: ollyvala/booking-service:1.0
    container_name: booking-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservations_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      HOTEL_SERVICE_HOST: hotel-service
      HOTEL_SERVICE_PORT: 8082
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty-service
      LOYALTY_SERVICE_PORT: 8085
    ports:
      - "8083:8083"
    networks:
      - net
    depends_on:
      - postgres
      - rabbitmq
      - hotel-service
      - payment-service
      - loyalty-service

  # 9. Gateway Service (фасад/API Gateway) – ГЛАВНЫЙ ДОСТУП
  gateway-service:
    image: ollyvala/gateway-service:1.0
    container_name: gateway-service
    environment:
      SESSION_SERVICE_HOST: session-service
      SESSION_SERVICE_PORT: 8081
      HOTEL_SERVICE_HOST: hotel-service
      HOTEL_SERVICE_PORT: 8082
      BOOKING_SERVICE_HOST: booking-service
      BOOKING_SERVICE_PORT: 8083
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty-service
      LOYALTY_SERVICE_PORT: 8085
      REPORT_SERVICE_HOST: report-service
      REPORT_SERVICE_PORT: 8086
    ports:
      - "8087:8087"
    networks:
      - net
    depends_on:
      - session-service
      - hotel-service
      - booking-service
      - payment-service
      - loyalty-service
      - report-service

  #   # 10. Nginx Reverse Proxy - ЕДИНСТВЕННЫЙ доступный извне
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"  # ТОЛЬКО этот порт открыт наружу
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - net
  #   depends_on:
  #     - gateway-service
  #     - session-service

volumes:
  postgres_data:
    driver: local