services:
  1part6:
    image: part5:1.0
    networks:
      - local

  2part6:
    image: nginx:1.27
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local
    depends_on:
      - 1part6

networks:
  local:
    driver: bridge