---
- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Start Apache
  systemd:
    name: apache2
    state: started
    enabled: yes

- name: Create simple index page
  copy:
    dest: /var/www/html/index.html
    content: |
      <html>
      <body>
        <h1>Apache on node02</h1>
        <p>PostgreSQL is also running here</p>
        <p>Connect: psql -h 192.168.94.158 -U postgres -d testdb</p>
      </body>
      </html>
    owner: www-data
    group: www-data